FROM ubuntu:focal

# Install curl, git, and Node.js (with npm included)
RUN apt-get update \
 && apt-get install -y curl git \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y nodejs \
 && npm install -g npm@latest \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/app

# Copy files
COPY main.sh script.js package*.json ./

# Install dependencies
RUN npm install

RUN chmod +x main.sh script.js

ENTRYPOINT ["/home/app/main.sh"]
